{% set pkgname = "gnuplot" %}
{% set version = "6.0.1" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/{{ pkgname }}/files/{{ pkgname }}/{{ version }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: e85a660c1a2a1808ff24f7e69981ffcbac66a45c9dcf711b65610b26ea71379a
  patches:
    - fix-doc-path.patch  # [build_platform != target_platform]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]

    - pkg-config
    - gnuconfig  # [unix]
    - make  # [unix]
    - libiconv  # [build_platform != target_platform and linux]

  host:
    - readline
    - libgd
    - cairo
    - pango
    - qt-main  # [not ppc64le]
    - glib

    - xorg-libx11  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxxf86vm  # [linux]

    - chrpath  # [linux]
    - gtk2  # [linux]
    - libiconv  # [linux]

test:
  files:
    - test-data.txt
  commands:
    - gnuplot -e "set terminal dumb; set style histogram; p 'test-data.txt'"
    - gnuplot -e "set terminal png"

about:
  home: https://github.com/gnuplot/gnuplot
  license: Gnuplot
  license_file: Copyright
  summary: Gnuplot, plotting from command line

extra:
  recipe-maintainers:
    - croth1
