{% set pkgname = "gnuplot" %}
{% set version = "5.0.6" %}
{% set sha256 = "5bbe4713e555c2e103b7d4ffd45fca69551fff09cf5c3f9cb17428aaacc9b460" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.gz
  url: https://sourceforge.net/projects/{{ pkgname }}/files/{{ pkgname }}/{{ version }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - pkgconfig
    - ncurses 5.9*
    - readline 6.2*
    - libgd
    - cairo 1.14.*
    - qt 5.6.*
    - pango 1.40.*
  run:
    - ncurses 5.9*
    - readline 6.2*
    - libgd
    - cairo 1.14.*
    - qt 5.6.*
    - pango 1.40.*

test:
  files:
    - test-data.txt
  commands:
    - gnuplot -e "set terminal dumb; set style histogram; p 'test-data.txt'"
    - gnuplot -e "set terminal png"
    - conda inspect linkages -p $PREFIX gnuplot  # [not win]
    - conda inspect objects -p $PREFIX gnuplot   # [osx]

about:
  home: https://github.com/gnuplot/gnuplot
  license: Gnuplot
  license_file: Copyright
  summary: Gnuplot, plotting from command line

extra:
  recipe-maintainers:
    - croth1
