{% set pkgname = "gnuplot" %}
{% set version = "6.0.1" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/{{ pkgname }}/files/{{ pkgname }}/{{ version }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: e85a660c1a2a1808ff24f7e69981ffcbac66a45c9dcf711b65610b26ea71379a
  patches:
    - fix-doc-path.patch  # [build_platform != target_platform]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('expat') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxrender') }}  # [linux]
    - {{ cdt('libxt') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - libxcb  # [linux]
    - pkg-config
    - gnuconfig  # [unix]
    - make  # [unix]
    - zlib  # [build_platform != target_platform]
  host:
    - ncurses
    - readline
    - libgd
    - cairo
    - pango
    - qt-main  # [not ppc64le]
    - freetype
    - glib
    - xorg-libX11  # [linux]
    - xorg-libxt  # [linux]
    - xorg-libxext  # [linux]
    - chrpath  # [linux]
    - xorg-libxrender  # [linux]
    - libxcb  # [linux]
    - gtk2  # [linux]
    - dbus  # [linux]
  run:
    - ncurses
    - readline
    - libgd
    - cairo
    - pango
    - qt-main  # [not ppc64le]
    - freetype
    - glib
    - xorg-libX11  # [linux]
    - xorg-libxt  # [linux]
    - xorg-libxext  # [linux]
    - chrpath  # [linux]
    - xorg-libxrender  # [linux]
    - gtk2  # [linux]
    - dbus  # [linux]

test:
  files:
    - test-data.txt
  commands:
    - gnuplot -e "set terminal dumb; set style histogram; p 'test-data.txt'"
    - gnuplot -e "set terminal png"

about:
  home: https://github.com/gnuplot/gnuplot
  license: Gnuplot
  license_file: Copyright
  summary: Gnuplot, plotting from command line

extra:
  recipe-maintainers:
    - croth1
