{% set pkgname = "gnuplot" %}
{% set version = "5.4.8" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/{{ pkgname }}/files/{{ pkgname }}/{{ version }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: 931279c7caad1aff7d46cb4766f1ff41c26d9be9daf0bcf0c79deeee3d91f5cf
  patches:
    - fix-doc-path.patch  # [build_platform != target_platform]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]

    - pkg-config
    - gnuconfig  # [unix]
    - make  # [unix]
    
    - xorg-libx11  # [(build_platform != target_platform) and linux]
    - xorg-libxdamage  # [build_platform != target_platform]
    - xorg-libxfixes  # [build_platform != target_platform]
    - xorg-libxxf86vm  # [build_platform != target_platform]
    
    - zlib  # [build_platform != target_platform]
    - libiconv  # [build_platform != target_platform]

  host:
    - readline
    - libgd
    - cairo
    - pango
    - qt-main  # [not ppc64le]
    - glib

    - xorg-libx11  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxxf86vm  # [linux]

    - chrpath  # [linux]
    - gtk2  # [linux]
    - libiconv  # [linux]

test:
  files:
    - test-data.txt
  commands:
    - gnuplot -e "set terminal dumb; set style histogram; p 'test-data.txt'"
    - gnuplot -e "set terminal png"

about:
  home: https://github.com/gnuplot/gnuplot
  license: Gnuplot
  license_file: Copyright
  summary: Gnuplot, plotting from command line

extra:
  recipe-maintainers:
    - croth1
